### ISSUE TITLE
Termux - Not an editor command

### ISSUE THREAD

**Issue by lmservas** [NormalNvim/NormalNvim#203]
Hello,

I just installed all the dependencies and NormalNVIM in the latest Termux debug build. Whenever I attempt to use one of the commands, or if I try to select "Update Plugins and Mason" from the menu I get the following error:

:healthcheck base
E492: Not an editor command: healthcheck base
Press ENTER or type command to continue

E492: Not an editor command: NvimUpdatePackages
Press ENTER or type command to continue

I'm not sure what to do to fix this?

Also when syncing plugins there is one failure as shown:

stickybuf.nvim      ■■ checkout failed
                fatal: not a git repository: .github/
                nvim_doc_tools/../../.git/modules/.github/
                nvim_doc_tools

**Comment by Zeioth** [comment]
Hello @lmservas thank you for reporting.

1. The right command is `:checkhealth base`
2. The right command is `:NvimUpdatePlugin`, or you can press `Space+pU`
3. The commit we were pointing ceased to exist. This has been fixed [here](https://github.com/NormalNvim/NormalNvim/commit/b59a4bd46cdb68c20e119be08f1277657f937005)

**Comment by Zeioth** [comment]
Copy the content of [this](https://github.com/NormalNvim/NormalNvim/blob/main/lua/lazy_snapshot.lua) into your `lazy_snapshop.lua` and you should be able to update `stickybuf` normally again.
