### ISSUE TITLE
Snapshot out of sync

### ISSUE THREAD

**Issue by doctorfree** [NormalNvim/NormalNvim#29]
Currently it appears the snapshot file and plugins entries for a couple of plugins are out of sync. In `lua/lazy_snapshot.lua` the entry for `friendly-snippets` uses the `rafamadriz` repository while the entry in `lua/plugins/4-dev.lua` uses the `zeioth` repo. Similarly, the entries for `bufdelete` do not use the same url. This causes Neovim 0.9 to issue warnings on startup.

Perhaps this can be resolved by simply re-generating the snapshot or switching to `nightly`.

I like your approach in this project and hope to be able to explore further as time permits. Thanks!

**Comment by Zeioth** [comment]
Thank you for your kind words 😊 
Locked versions have been refreshed.

**Comment by Zeioth** [comment]
btw zeioth/friendly snippets implements this in case you are curious
https://github.com/rafamadriz/friendly-snippets/issues/327

will revert back to rafamadriz once he finds spare time to merge it. Same thing for the spectre UI patches.

**Comment by doctorfree** [comment]
Warnings are gone now, thanks for the prompt response. I will play around with this config and add it to my [lazyman project](https://github.com/doctorfree/nvim-lazyman). Good work.
