### ISSUE TITLE
ctrl+d to go "down" whilst skimming a document deletes a line instead 

### ISSUE THREAD

**Issue by starkers** [NormalNvim/NormalNvim#352]
this mapping I think conflicts with "normal" vim behaviour..

I'd suggest not mapping this to `dd` (I assume) on default please

Over-all impressive distro so far btw; still testing it out but hope you don't mind some friendly feedback

The golang presets are decent!

Cheers

**Comment by Zeioth** [comment]
@starkers Very happy to hear you like it so far. You can revert `dd` to the modern vim behavior on `1-options.lua` deleting the option:

```lua
vim.opt.selection = "old"
```

**Comment by Zeioth** [comment]
About `C-d` this is the way is mapped:

```lua
if not is_android then
-- only useful when the option clipboard is commented on ./1-options.lua
maps.n["<C-y>"] = { '"+y<esc>', desc = "Copy to cliboard" }
maps.x["<C-y>"] = { '"+y<esc>', desc = "Copy to cliboard" }
maps.n["<C-d>"] = { '"+y<esc>dd', desc = "Copy to clipboard and delete line" }
maps.x["<C-d>"] = { '"+y<esc>dd', desc = "Copy to clipboard and delete line" }
maps.n["<C-p>"] = { '"+p<esc>', desc = "Paste from clipboard" }
end
```

And the old `ctrl+d` [has been improved](https://github.com/NormalNvim/NormalNvim/wiki/cool-tricks#quick-movement) to be more flexible.

Of course it's totally cool to remap it to anything you like.
