### ISSUE TITLE
Possibly changing telescope to fzf-lua

### ISSUE THREAD

**Issue by premell** [NormalNvim/NormalNvim#36]
A rather controversial opinion but i think fzf-lua is better than telescope. It is atleast 100x faster (you can really really feel it if you just have a few thousand files in your project). Fzf-lua is also quite mature and have all the expected features. It can fuzzy find text, it can change colorschemes with preview, it has highlighted text in its file preview and many other builtin features. 

Repo: https://github.com/ibhagwan/fzf-lua

Note: it's good practice to first [read the script](https://github.com/ibhagwan/fzf-lua/blob/main/scripts/mini.sh) before running sh -c directly from the web

Test it without changing your config: sh -c "$(curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh)"

pros: 
100x faster

cons: 
not as widely adopted as telescope
if you have very custom queries it might be easier with telescope

**Comment by Zeioth** [comment]
The distro is mean to be used as personal config, so feel free to do the change. Quite a few plugins rely on Telescope though, it will require a bit of work.
