### ISSUE TITLE
Debugging on Windows disabled

### ISSUE THREAD

**Issue by Miconen** [NormalNvim/NormalNvim#370]
Been loving using NormalNvim for the past few weeks. Came across this line in the debugger section and couldn't find any more information as to why it is disabled on Windows. Would be nice to have some sort of documentation for the reason behind it ^^

```lua
-- lua/plugins/4-dev.lua

"mfussenegger/nvim-dap",
enabled = vim.fn.has "win32" == 0,
...
```

**Comment by Zeioth** [comment]
@Miconen No user has tested it on Windows yet. If you can remove that line and test it, we could enable it for Windows, if DAP is actually supported on that platform.

**Comment by Miconen** [comment]
As you asked, I did some very surface level testing as i'm not the most experienced with debugging, let alone in nvim. I tested with TypeScript (firefox-debug-adapter) and Go (delve)

### TypeScript:
`AppData\Local\nvim-data/mason/bin/firefox-debug-adapter: ENOENT: no such file or directory
stack traceback:`

Changing this line in the 4-dev.lua to include a ".cmd" extensions at the end of it spawned a blank new terminal window running node without sign of life.
```lua
command = vim.fn.stdpath('data')..'/mason/bin/firefox-debug-adapter',
```
Notifications
```
Debug adapter didn't respond. Either the adapter is slow (then wait and ignore this) or there is a problem with your adapter or `firefox` configuration. Check the logs for errors (:help dap.set_log_level)

`AppData\Local\nvim-data/mason/bin/firefox-debug-adapter.cmd exited with code: 3221225786`
```

`:DapShowLog`
```
[ ERROR ] 2024-03-24T01:11:48Z+0200 ] ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:1438 ]	"stderr"	{
  command = "AppData\\Local\\nvim-data/mason/bin/firefox-debug-adapter.cmd",
  type = "executable"
}	"^C"
```

### Go

Notifications
```
Debug adapter didn't respond. Either the adapter is slow (then wait and ignore this) or there is a problem with your adapter or `delve` configuration. Check the logs for errors (:help dap.set_log_level)

AppData\Local\nvim-data/mason/packages/delve/dlv exited with code 2

ECONNRESET
```
`:DapShowLog`
```
[ DEBUG ] 2024-03-24T01:18:12Z+0200 ] ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:1683 ]	"request"	{
  arguments = {
    restart = false,
    terminateDebuggee = true
  },
  command = "disconnect",
  seq = 2,
  type = "request"
}
```

**Comment by Miconen** [comment]
I think it could warrant at the very least a warning/disclaimer comment/documentation of why it is disabled on Windows to avoid confusion. 👍

**Comment by Zeioth** [comment]
Yeah. Let's close it for now. If you manage to make it work feel free to reopen 😊
