### ISSUE TITLE
is_android always true

### ISSUE THREAD

**Issue by emretuna** [NormalNvim/NormalNvim#373]
I'm on osx and is_android always returns true.

**Comment by Zeioth** [comment]
@emretuna this is the line we use to detect android:
```lua
local is_android = vim.fn.isdirectory('/system') == 1   -- true if on android
```
Could you please check if osx have a /system directory in the root directory? Because if so we might have to find a different solution.

**Comment by Zeioth** [comment]
Ok it seems it does:
![it does](https://github.com/NormalNvim/NormalNvim/assets/3357792/083b0692-3a91-4058-89ed-1c49084af199)

Thank you for making me aware of this. Let me work on it today. If you find a solution please feel free to write here or send a PR.

**Comment by Zeioth** [comment]
We now do 
```lua
local is_android = vim.fn.isdirectory('/data') == 1   -- true if on android
```
Which is a directory only android has. So it should be fixed now.
