### ISSUE TITLE
python venv doesn't work

### ISSUE THREAD

**Issue by yuvenhol** [NormalNvim/NormalNvim#376]

**Comment by Zeioth** [comment]
This issue doesn't show a minimum level of research or information. Closing.

**Comment by Zeioth** [comment]
Plus, it is working, as you can see on the bottom right (venv name, my_env in this case).
```
# Create a virtual environment named 'my_env'
python3 -m venv my_env

# Activate the virtual environment on Unix/macOS
source my_env/bin/activate
```
![screenshot_2024-03-28_11-45-08_000839918](https://github.com/NormalNvim/NormalNvim/assets/3357792/d569c2a4-f88b-4e7f-9e9b-b80347d98182)
