### ISSUE TITLE
Diagnostics doesn't respect the screen width.

### ISSUE THREAD

**Issue by agoodfellow123** [NormalNvim/NormalNvim#378]
I am quite aware this isn't a fault on normalnvim's part but since I don't know which plugin causes this I have decided to write here. So the problem could be seen in the image:

![image](https://github.com/NormalNvim/NormalNvim/assets/36235265/13605d50-dc52-430c-9177-6b724839b1d9)

As you can see the warning diagnostic message gets cut and there is no way to read it all because you can not scroll to non-existent text in nvim. I already found a roundabout solution.

Normalnvim comes with this line in 4-mappings.lua: `lsp_mappings.n["<leader>ld"] = { function() vim.diagnostic.open_float() end, desc = "Hover diagnostics" }`

So I added this line over it to use it in a more accessible way: `lsp_mappings.n["<Tab>"] = { function() vim.diagnostic.open_float() end }`

With this anytime in normal mode when you press tab you can see the warning or error messages as a hovering box.

As a side issue: the warnings on workspace diagnostics menu also cuts:
![image](https://github.com/NormalNvim/NormalNvim/assets/36235265/a63a2bcb-0b84-4ad9-8fe4-5664fe724613)

**Comment by Zeioth** [comment]
Welcome!

Press `Space + u + d` to cycle through all the available diagnostic modes. When you find the one you like, you can make the changes permanent [here](https://github.com/NormalNvim/NormalNvim/blob/e909ca7eaee571a17843dd3fe45fb0fe4a7de34d/lua/base/1-options.lua#L82):

**Comment by agoodfellow123** [comment]
Hello! I have tried Space + u + d. Unfortunately, none of the modes solves the problem I mentioned. Which is the virtual text cutting off. The other modes just disables the text instead.

**Comment by Zeioth** [comment]
Then I'm afraid we can't do anything. Neovim implements it that way.

**Comment by agoodfellow123** [comment]
Got it, thank you for the clarification! One more thing, can you please tell me which plugin puts lsp messages to this virtual text? Perhaps I can fix it if I can find anything on it.

**Comment by Zeioth** [comment]
On the botton right of the status bar you have the LSP clients of your current filetype:
![screenshot_2024-03-31_01-29-08_779917319](https://github.com/NormalNvim/NormalNvim/assets/3357792/3e78b7b7-9a2d-4866-b214-f27acd5141bf)

* Press `Space + p + m` to open the package manager of LSP clients (mason).
* To filter only the one you are using, press `ctrl+f` to choose a language, and then `4` to show only the linter.

**Comment by Zeioth** [comment]
Also feel welcome to join the discord channel if you have more questions 👍
https://discord.com/invite/ymcMaSnq7d

**Comment by agoodfellow123** [comment]
I highly doubt this is about the lsp client because both ruff (python) and rust-analyzer messages cut off the same way. Thank you for the discord invitation. I'll be checking it out in a moment.
