### ISSUE TITLE
Markdown loses linebreaks

### ISSUE THREAD

**Issue by Crashdummyy** [NormalNvim/NormalNvim#383]
The [Markdown Documentation](https://www.markdownguide.org/basic-syntax/#line-breaks) states:
> To create a line break or new line (<br>), end a line with two or more spaces, and then type return.

The moment I save my changes those two trailing whitespace characters are removed.
I already uninstalled prettier and markdownlint but that one doesnt help.

This is the information of my none-ls:

```
	null-ls
	https://github.com/nvimtools/none-ls.nvim
	
	Logging
	* current level: warn
	* path: /home/crashdummy/.cache/nvim/null-ls.log
	
	Active source(s)
	* name: prettier
	* filetypes: yaml | graphql | html | less | markdown | typescriptreact | javascriptreact | handlebars | css | jsonc | scss | json | markdown.mdx | javascript | vue | typescript
	* methods: range_formatting | formatting
	
	* name: markdownlint
	* filetypes: markdown | markdown.mdx
	* methods: diagnostics
	
	* name: markdownlint
	* filetypes: markdown
	* methods: formatting
	
	
	Supported source(s)
	* hover: dictionary
	* code_actions: proselint
	* diagnostics: alex | ltrs | ltrs | markdownlint | markdownlint_cli2 | mdl | proselint | textidote | textlint | vale | write_good
	* formatting: cbfmt | markdownlint | mdformat | ocdc | prettier | prettierd | remark | textlint
```

How can I prevent this behavior ?

**Comment by Zeioth** [comment]
Hello @Crashdummyy sorry for the unusually long time to answer.
That's the plugin trim.nvim you can find on [plugins/1-behavior.lua](https://github.com/NormalNvim/NormalNvim/blob/d724e6c760f0c781bf2b2dc32e0367e559610a81/lua/plugins/1-base-behaviors.lua#L99).

And I agree it should not trigger on markdown files. I'm gonna research this change for NormalNvim 3.8, comming in a few days.
