### ISSUE TITLE
compatibility with flutter-tools

### ISSUE THREAD

**Issue by mictadlo** [NormalNvim/NormalNvim#391]
Hi,
Is NormalNvim compatible with [flutter-tools](https://github.com/akinsho/flutter-tools.nvim)?

Thank you in advance,

Best wishes,

Michal

**Comment by Zeioth** [comment]
@mictadlo Yes! 

We also we ship a flutter compiler if you press `F6`. Just make sure you are in the right directory with `:cd <your-project-root>`. You can read more [here](https://github.com/Zeioth/compiler.nvim/wiki/dart-compiler).

Other features we support for flutter:
* lsp, linting, formatting, code actions.
* [debugger](https://github.com/Zeioth/compiler.nvim/wiki/DAP-support-dart).
* Unit tests.
* [Code coverage](https://github.com/NormalNvim/NormalNvim/releases/tag/v3.8.3).

All it's pre-configured and ready to use. But let me know if you find any issue during your experience ❤️
