### ISSUE TITLE
small bugs

### ISSUE THREAD

**Issue by thederpykrafter** [NormalNvim/NormalNvim#399]
first off i love the focus on termux and look forward to setting up my own config to be more os centric. 

I occasionally have problems with the cursor selection moving off of the dashboard shortcuts which renders them useless.
I also sometimes get stuck on a blank page and whichkey bindings dont work eg. `<leader>e` wont open neotree. 
In both scenarios normal vim commands still work eg. `<cmd>q` still quits.

everything is working great on termux otherwise.

I have yet to figure out a way to reproduce the issue.

**Comment by Zeioth** [comment]
cannot repro
![Screenshot_20240519_015105_Termux.jpg](https://github.com/NormalNvim/NormalNvim/assets/3357792/21b93457-60e4-42cf-a259-68907109af57)


A video showing the bugs might help. Also I advice trying an unmodified version of NormalNvim.
