### ISSUE TITLE
Syntax highlight has to be toggled

### ISSUE THREAD

**Issue by Crashdummyy** [NormalNvim/NormalNvim#460]
For whatever reason it appears like syntax highlighting does not automatically works.

Let's say I open a yml file which is backed by a few lsps
![image](https://github.com/NormalNvim/NormalNvim/assets/15139403/3cc4cafa-dfac-43eb-a9db-edeb3f1b00fc)

after toggling with `<leader>u+y`

![image](https://github.com/NormalNvim/NormalNvim/assets/15139403/68e2b6b8-3133-45ef-8bc4-7bd319c98269)

**Comment by Zeioth** [comment]
@Crashdummyy I've reinstalled NormalNvim from scratch following [the instructions](https://github.com/NormalNvim/NormalNvim?tab=readme-ov-file#how-to-install) and I can't repro. Please feel free to provide more detail.
![screenshot_2024-07-01_11-23-50_585961647](https://github.com/NormalNvim/NormalNvim/assets/3357792/95139989-476d-4504-968b-aaeeed86c42f)

**Comment by Zeioth** [comment]
@Crashdummyy are you on neovim 0.10?

**Comment by Zeioth** [comment]
If what fixes it on your end is this...
> ```diff
> +vim.api.nvim_create_autocmd("FileType", {
> +  pattern = "cs",
> +  callback = function()
> +    utils.trigger_event("User csFile")
> +    require'nvim-treesitter.configs'.setup {
> +      highlight = {
> +        enable = true,
> +      }
> +    }
> +  end
> +})
> ```
> 

@Crashdummyy could you remove this `disable` block and see if that fixes it?
https://github.com/NormalNvim/NormalNvim/blob/ed7460f1a76e39932527270b541a6dbce319557d/lua/plugins/3-dev-core.lua#L71

**Comment by Zeioth** [comment]
@Crashdummyy I advice you to disable plugins until you isolate the issue. Please let me know if you solve it.
