### ISSUE TITLE
 potential issue in Termux with Tree-sitter Syntax Highlighting in NormalNvim.

### ISSUE THREAD

**Issue by niiniyare** [NormalNvim/NormalNvim#462]
## Potential Issue with Tree-sitter Syntax Highlighting in NormalNvim

I'm encountering a potential issue with Tree-sitter syntax highlighting in NormalNvim. Specifically, automatic syntax highlighting isn't working for certain file types, such as Go files. Manual enabling through `:TSEnable highlight` seems to be a workaround, but the expected automatic behavior is not observed.

It's unclear if this is an issue specific to the Termux environment or potentially limited to Go files. Syntax highlighting appears to be functioning correctly for other languages, like Lua, within the same environment.

I'd appreciate any insights into this behavior. Are there known limitations or configurations specific to Termux or Go files that might be affecting Tree-sitter? Additionally, if there are any debugging steps I can take to assist in further investigation, please let me know.

Thank you for your time and support.

**Comment by Zeioth** [comment]
Sorry for the small delay, I was stuck in a job interview until right now: I cannot repro (foot + tmux + NormalNvim).

![screenshot_2024-07-05_18-09-11_413474893](https://github.com/NormalNvim/NormalNvim/assets/3357792/1e3250f8-b9db-4506-b747-3d4b8216052b)

But @crashdummyy reported the same:
https://github.com/NormalNvim/NormalNvim/issues/460

It would be nice to discover the exact point of the code that is producing this. My best guess is [here](https://github.com/NormalNvim/NormalNvim/blob/ed7460f1a76e39932527270b541a6dbce319557d/lua/plugins/3-dev-core.lua#L71), but crashdummyy told me removing that doesn't fix it.

**Comment by Zeioth** [comment]
Hopefuly fixed in NormalNvim v3.9.8
