### ISSUE TITLE
Error when opening the file exporer with space+r

### ISSUE THREAD

**Issue by mobedoor** [NormalNvim/NormalNvim#486]
Get the following error when opening file explorer
```
error: unexpected argument '--client-id' found                                                                                       │
│                                                                                                                                     │
│  tip: to pass '--client-id' as a value, use '-- --client-id' 
```
yazi: 0.2.5
NormalNvim: v4.0.0 - Release candidate 2

**Comment by Zeioth** [comment]
@mobedoor thank you for reporting. I've just tested and that issue only happen if you are using an old version of yazi. It's not present when using the vesion from the yazi github repository.

In the meantime I'm gonna publish release candidate 3 with `use_yazi_client_id_flag = true`.

**Comment by Zeioth** [comment]
It should be fixed now!!
https://github.com/NormalNvim/NormalNvim/releases/tag/v4.0.0-rc3

**Comment by SimonSchwendele** [comment]
got this one as well.
When you install yazi through cargo it installs a different yazi-cli and yazi-fm version.
You can see this in :checkhealth

Downloading the Release in github manually solves this problem as well

**Comment by Zeioth** [comment]
@SimonSchwendele According to cargo it install yazi 0.25
https://crates.io/crates/yazi-fm/versions

Because we've set use_yazi_client_id_flag = false in `NormalNvim v4.0.0 release candidate 3`, it should work fine in that version. Please let me know if that's not your case.

**Comment by Zeioth** [comment]
I've catched a couple bugs (they got introduced because I was using the development version of yazi.nvim I use to send them PRs).
https://github.com/NormalNvim/NormalNvim/commit/f45ba7718279a38530906f32beb2c05c7e17e45b

RC4 released. Hopefuly all should be ok now.
https://github.com/NormalNvim/NormalNvim/releases/tag/v4.0.0-rc4

**Comment by Zeioth** [comment]
I've also fould yazi don't ship `ya` on termux, which is necessary to use `yazi.nvim`. issue opened on termux:
https://github.com/termux/termux-packages/issues/21054

**Comment by mobedoor** [comment]
Fixed for me. Thank you so much.

**Comment by SimonSchwendele** [comment]
No idea whether its just on my system but yazi navigates far slower than ranger used to

**Comment by Zeioth** [comment]
@SimonSchwendele out of curiosity. In which scenario?

**Comment by SimonSchwendele** [comment]
> @SimonSchwendele out of curiosity. In which scenario?

Huh okay its not that yazi itself is slower.
The keyboardnavigation is like more delayed.

When I keep j or k pressed it navigates similarily fast.
But when I press those buttons repeatedly it sometimes "skips" a buttonpress like my keyboard would start ghosting.
Very weird

**Comment by Zeioth** [comment]
@SimonSchwendele slightly yes. I notice too. It's more a OCD thing than a real annoyance. I think it's because Yazi uses multi threading. Hopefully it's gonna improve over time. They release big performance improvements every version.

**Comment by SimonSchwendele** [comment]
> @SimonSchwendele slightly yes. I notice too. It's more a OCD thing than a real annoyance. I think it's because Yazi uses multi threading. Hopefully it's gonna improve over time. They release big performance improvements every version.

Thats great and thanks for being so active on this project and other ones like compiler.nvim.
I'd love [my PR](https://github.com/Zeioth/compiler.nvim/pull/51) being reviewed tho 🙈
