### ISSUE TITLE
/Local/nvim/lua/base/2-lazy.lua:26: attempt to index field 'uv' (a nil value)

### ISSUE THREAD

**Issue by BibhutiSingh** [NormalNvim/NormalNvim#492]
Post cloning to windows (using cmd). nvim doesn't start up with following error 

/Local/nvim/lua/base/2-lazy.lua:26: attempt to index field 'uv' (a nil value)

**Comment by Zeioth** [comment]
@BibhutiSingh you are likely to be using a deprecated vesion of Neovim. You need `Neovim 0.10` or upper.
