### ISSUE TITLE
ollama integraton

### ISSUE THREAD

**Issue by mobedoor** [NormalNvim/NormalNvim#495]
Hello. I'm stingy with my Open AI credit and would like to use a local model when possible. Could you integrate ollama?

**Comment by Zeioth** [comment]
hello @mobedoor, I really want to ship it with the distro, but smartphones and most computers are not powerful enough to do so. We are gonna have to hold it for some time and stick with neural/copilot in the meantime.

But of course you can use ollama plugins on your machine!
