### ISSUE TITLE
lazy.nvim vs. NormalNvim

### ISSUE THREAD

**Issue by maitra** [NormalNvim/NormalNvim#515]
A new nvim user here, just wondering on the benefits of  NormalNvim vs. LazyNvim. Any drawbacks?

**Comment by maitra** [comment]
Thanks, so this is the difference with LazyNvim. I am especially interested in using R.nvim: will NormalNvim work with that out of the box? I can not find any example of anyone using it online.

**Comment by Zeioth** [comment]
Yes. R is supported out of the box.

If you want to change a LSP client just press `space + p + m` and you can customize them on the fly. I recommend you to read the [keymappings](https://normalnvim.github.io/docs/keymaps/), and [the description of every plugin](https://normalnvim.github.io/docs/plugins/behaviors/) to get to have a better idea of the features included.

Also, pass by to say hi on our discord channel!
